from enum import Enum


class IntentLabel(str, Enum):
    FACT = "FACT"
    SUMMARY = "SUMMARY"
    COMPARISON = "COMPARISON"
    METHOD_CONTEXT = "METHOD_CONTEXT"
    LIMITATION = "LIMITATION"
    TREND_PATTERN = "TREND_PATTERN"
    EXPLANATION = "EXPLANATION"
    SOURCE_SEEKING = "SOURCE_SEEKING"
    NAVIGATION = "NAVIGATION"
    INTERPRETATION = "INTERPRETATION"
    DECISION_SUPPORT = "DECISION_SUPPORT"
    FOLLOWUP = "FOLLOWUP"
    UNKNOWN = "UNKNOWN"
