#!/usr/bin/env bash

export HOWIE_PLANNER_LLM_BASE_URL="${HOWIE_PLANNER_LLM_BASE_URL:-http://localhost:8001}"
export HOWIE_PLANNER_LLM_MODEL="${HOWIE_PLANNER_LLM_MODEL:-Qwen/Qwen2.5-3B-Instruct}"

printf 'HOWIE_PLANNER_LLM_BASE_URL=%s\n' "$HOWIE_PLANNER_LLM_BASE_URL"
printf 'HOWIE_PLANNER_LLM_MODEL=%s\n' "$HOWIE_PLANNER_LLM_MODEL"
